# Generated by Django 4.2.15 on 2025-06-23 02:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0004_alter_userapisecret_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="domain",
            field=models.CharField(default="domain.com", max_length=100),
        ),
    ]
