# Generated by Django 4.2.22 on 2025-09-23 08:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0005_user_domain"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userapisecret",
            name="team",
            field=models.IntegerField(default=0),
        ),
    ]
