# Generated by Django 4.2.7 on 2025-07-18 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DataSourceAPIModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created Time")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated Time")),
                ("created_by", models.CharField(default="", max_length=32, verbose_name="Creator")),
                ("updated_by", models.CharField(default="", max_length=32, verbose_name="Updater")),
                ("domain", models.CharField(default="domain.com", max_length=100, verbose_name="Domain")),
                (
                    "updated_by_domain",
                    models.CharField(default="domain.com", max_length=100, verbose_name="updated by domain"),
                ),
                ("name", models.CharField(max_length=255, unique=True, verbose_name="数据源名称")),
                ("rest_api", models.CharField(max_length=255, unique=True, verbose_name="REST API URL")),
                ("desc", models.TextField(blank=True, null=True, verbose_name="描述")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                ("params", models.JSONField(blank=True, help_text="API请求参数", null=True, verbose_name="请求参数")),
            ],
            options={
                "verbose_name": "数据源API",
                "verbose_name_plural": "数据源API",
                "db_table": "operation_analysis_data_source_api",
                "ordering": ["-created_at"],
            },
        ),
    ]
