# Generated by Django 4.2.7 on 2025-07-22 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("operation_analysis", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(name="datasourceapimodel", options={"verbose_name": "数据源API"},),
        migrations.CreateModel(
            name="Dashboard",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created Time")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated Time")),
                ("created_by", models.CharField(default="", max_length=32, verbose_name="Creator")),
                ("updated_by", models.CharField(default="", max_length=32, verbose_name="Updater")),
                ("domain", models.CharField(default="domain.com", max_length=100, verbose_name="Domain")),
                (
                    "updated_by_domain",
                    models.CharField(default="domain.com", max_length=100, verbose_name="updated by domain"),
                ),
                ("name", models.CharField(max_length=128, verbose_name="仪表盘名称")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("gauge", "仪表盘"),
                            ("line", "折线图"),
                            ("bar", "柱状图"),
                            ("pie", "饼图"),
                            ("scatter", "散点图"),
                            ("map", "地图"),
                            ("text", "文本"),
                        ],
                        max_length=64,
                        verbose_name="仪表盘类型",
                    ),
                ),
                ("filters", models.JSONField(blank=True, help_text="仪表盘过滤条件", null=True, verbose_name="过滤条件")),
                ("other", models.JSONField(blank=True, help_text="其他配置", null=True, verbose_name="其他配置")),
                (
                    "data_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboards",
                        to="operation_analysis.datasourceapimodel",
                        verbose_name="数据源",
                    ),
                ),
            ],
            options={"verbose_name": "仪表盘", "db_table": "operation_analysis_dashboard",},
        ),
        migrations.AddConstraint(
            model_name="dashboard",
            constraint=models.UniqueConstraint(fields=("name", "type"), name="unique_session_event"),
        ),
    ]
