# Generated by Django 4.2.7 on 2025-07-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operation_analysis", "0002_alter_datasourceapimodel_options_dashboard_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(model_name="dashboard", name="unique_session_event",),
        migrations.AlterField(
            model_name="datasourceapimodel", name="name", field=models.CharField(max_length=255, verbose_name="数据源名称"),
        ),
        migrations.AlterField(
            model_name="datasourceapimodel",
            name="rest_api",
            field=models.CharField(max_length=255, verbose_name="REST API URL"),
        ),
        migrations.AddConstraint(
            model_name="dashboard",
            constraint=models.UniqueConstraint(fields=("name", "type"), name="unique_name_type"),
        ),
        migrations.AddConstraint(
            model_name="datasourceapimodel",
            constraint=models.UniqueConstraint(fields=("name", "rest_api"), name="unique_name_rest_api"),
        ),
    ]
