# Generated by Django 4.2.7 on 2025-07-31 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("operation_analysis", "0004_directory_remove_dashboard_unique_name_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Topology",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created Time")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated Time")),
                ("created_by", models.CharField(default="", max_length=32, verbose_name="Creator")),
                ("updated_by", models.CharField(default="", max_length=32, verbose_name="Updater")),
                ("domain", models.CharField(default="domain.com", max_length=100, verbose_name="Domain")),
                (
                    "updated_by_domain",
                    models.CharField(default="domain.com", max_length=100, verbose_name="updated by domain"),
                ),
                ("name", models.CharField(max_length=128, unique=True, verbose_name="拓扑图名称")),
                ("desc", models.TextField(blank=True, null=True, verbose_name="描述")),
                ("other", models.JSONField(blank=True, help_text="拓扑图其他配置", null=True)),
                ("view_sets", models.JSONField(default=list, help_text="拓扑图视图集配置")),
                (
                    "directory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topology",
                        to="operation_analysis.directory",
                        verbose_name="所属目录",
                    ),
                ),
            ],
            options={"verbose_name": "拓扑图", "db_table": "operation_analysis_topology",},
        ),
    ]
