# Generated by Django 4.2.7 on 2025-08-06 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operation_analysis", "0005_topology"),
    ]

    operations = [
        migrations.CreateModel(
            name="NameSpace",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created Time")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated Time")),
                ("created_by", models.CharField(default="", max_length=32, verbose_name="Creator")),
                ("updated_by", models.CharField(default="", max_length=32, verbose_name="Updater")),
                (
                    "updated_by_domain",
                    models.CharField(default="domain.com", max_length=100, verbose_name="updated by domain"),
                ),
                ("name", models.CharField(max_length=128, unique=True, verbose_name="命名空间名称")),
                ("account", models.CharField(max_length=64, verbose_name="账号")),
                ("password", models.CharField(max_length=128, verbose_name="密码")),
                ("domain", models.CharField(max_length=255, verbose_name="域名")),
                ("desc", models.TextField(blank=True, null=True, verbose_name="描述")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
            ],
            options={"verbose_name": "命名空间", "db_table": "operation_analysis_namespace",},
        ),
        migrations.AddField(
            model_name="datasourceapimodel",
            name="namespaces",
            field=models.ManyToManyField(
                blank=True,
                help_text="会话关联的事件",
                related_name="data_sources",
                to="operation_analysis.namespace",
                verbose_name="命名空间",
            ),
        ),
    ]
