# Generated by Django 4.2.7 on 2025-09-03 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operation_analysis", "0006_namespace_datasourceapimodel_namespaces"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataSourceTag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created Time")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated Time")),
                ("created_by", models.CharField(default="", max_length=32, verbose_name="Creator")),
                ("updated_by", models.CharField(default="", max_length=32, verbose_name="Updater")),
                ("domain", models.CharField(default="domain.com", max_length=100, verbose_name="Domain")),
                (
                    "updated_by_domain",
                    models.CharField(default="domain.com", max_length=100, verbose_name="updated by domain"),
                ),
                ("tag_id", models.CharField(max_length=64, unique=True, verbose_name="标签id")),
                ("name", models.CharField(max_length=64, unique=True, verbose_name="标签名称")),
                ("desc", models.TextField(blank=True, null=True, verbose_name="描述")),
                ("build_in", models.BooleanField(default=False, verbose_name="是否内置")),
            ],
            options={"verbose_name": "数据源标签", "db_table": "operation_analysis_data_source_tag",},
        ),
        migrations.AddField(
            model_name="datasourceapimodel",
            name="chart_type",
            field=models.JSONField(blank=True, default=list, help_text="图表类型", null=True),
        ),
        migrations.AddField(
            model_name="datasourceapimodel",
            name="tag",
            field=models.ManyToManyField(
                blank=True, help_text="数据源标签", related_name="data_sources", to="operation_analysis.datasourcetag"
            ),
        ),
    ]
