# Generated by Django 4.2.7 on 2025-06-26 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemSetting",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created Time")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated Time")),
                ("key", models.CharField(help_text="设置键", max_length=100, unique=True)),
                ("value", models.JSONField(default=dict, help_text="设置值")),
                ("description", models.TextField(blank=True, help_text="设置描述", null=True)),
                ("is_activate", models.BooleanField(db_index=True, default=False, help_text="是否启用")),
                ("is_build", models.BooleanField(db_index=True, default=True, help_text="是否为内置设置")),
            ],
            options={"verbose_name": "系统设置", "verbose_name_plural": "系统设置", "db_table": "alerts_system_setting",},
        ),
    ]
