# Generated by Django 4.2.7 on 2025-06-04 02:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alerts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Level",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("level_id", models.SmallIntegerField(help_text="级别ID")),
                ("level_name", models.CharField(help_text="级别名称", max_length=32)),
                ("level_display_name", models.CharField(help_text="级别中文名称", max_length=32)),
                ("color", models.CharField(blank=True, help_text="颜色代码", max_length=16, null=True)),
                ("icon", models.TextField(blank=True, help_text="图标base64", null=True)),
                ("description", models.CharField(blank=True, help_text="级别描述", max_length=300, null=True)),
                (
                    "level_type",
                    models.CharField(
                        choices=[("event", "事件"), ("alert", "告警"), ("incident", "事故")], help_text="级别类型",
                        max_length=32
                    ),
                ),
                ("built_in", models.BooleanField(default=False, help_text="是否为内置级别"))
            ],
            options={"db_table": "alerts_level", },
        ),
        migrations.AlterField(
            model_name="alert", name="level", field=models.CharField(db_index=True, help_text="级别", max_length=32),
        ),
        migrations.AlterField(
            model_name="event", name="level", field=models.CharField(db_index=True, help_text="级别", max_length=32),
        ),
        migrations.AddConstraint(
            model_name="level",
            constraint=models.UniqueConstraint(fields=("level_id", "level_type"), name="unique_level_id_level_type"),
        ),
    ]
