# Generated by Django 4.2.7 on 2025-06-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0002_level_alter_alert_level_alter_event_level_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertAssignment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created Time")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated Time")),
                ("created_by", models.CharField(default="", max_length=32, verbose_name="Creator")),
                ("updated_by", models.CharField(default="", max_length=32, verbose_name="Updater")),
                ("name", models.CharField(help_text="分派策略名称", max_length=200, unique=True)),
                (
                    "match_type",
                    models.CharField(choices=[("all", "全部匹配"), ("filter", "过滤匹配")], help_text="匹配类型", max_length=32),
                ),
                ("match_rules", models.JSONField(blank=True, default=dict, help_text="匹配规则", null=True)),
                ("personnel", models.JSONField(blank=True, default=list, help_text="分派人员", null=True)),
                (
                    "notify_channels",
                    models.CharField(
                        choices=[("email", "邮件"), ("enterprise_wechat", "企业微信")],
                        default="email",
                        help_text="通知渠道",
                        max_length=64,
                    ),
                ),
                (
                    "notification_scenario",
                    models.CharField(
                        choices=[("Assignment", "分派"), ("recovered", "恢复")],
                        default="Assignment",
                        help_text="通知场景",
                        max_length=32,
                    ),
                ),
                ("config", models.JSONField(default=dict, help_text="分派配置")),
                ("notification_frequency", models.JSONField(blank=True, default=dict, help_text="通知频率配置", null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True, help_text="是否启用")),
            ],
            options={"db_table": "alerts_alert_assignment",},
        ),
        migrations.CreateModel(
            name="AlertShield",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created Time")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated Time")),
                ("created_by", models.CharField(default="", max_length=32, verbose_name="Creator")),
                ("updated_by", models.CharField(default="", max_length=32, verbose_name="Updater")),
                ("name", models.CharField(help_text="屏蔽策略名称", max_length=200, unique=True)),
                (
                    "match_type",
                    models.CharField(choices=[("all", "全部匹配"), ("filter", "过滤匹配")], help_text="匹配类型", max_length=32),
                ),
                ("match_rules", models.JSONField(blank=True, default=dict, help_text="匹配规则", null=True)),
                ("suppression_time", models.JSONField(default=dict, help_text="屏蔽时间配置")),
                ("is_active", models.BooleanField(db_index=True, default=True, help_text="是否启用")),
            ],
            options={"db_table": "alerts_alert_shield",},
        ),
    ]
