# Generated by Django 4.2.7 on 2025-06-26 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0002_systemsetting"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotifyResult",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("notify_people", models.JSONField(default=list, help_text="通知人员")),
                ("notify_channel", models.CharField(blank=True, help_text="通知渠道", max_length=100, null=True)),
                ("notify_channel_name", models.CharField(blank=True, help_text="通知渠道名称", max_length=100, null=True)),
                ("notify_time", models.DateTimeField(auto_now_add=True, help_text="通知时间")),
                (
                    "notify_result",
                    models.CharField(
                        choices=[("success", "成功"), ("failed", "失败"), ("partial_success", "部分成功")],
                        help_text="通知结果",
                        max_length=30,
                    ),
                ),
                ("notify_object", models.CharField(blank=True, help_text="通知对象ID", max_length=100, null=True)),
                ("notify_type", models.CharField(blank=True, help_text="通知类型", max_length=50, null=True)),
            ],
            options={"verbose_name": "通知结果", "verbose_name_plural": "通知结果", "db_table": "alerts_notify_result",},
        ),
    ]
