# Generated by Django 4.2.7 on 2025-06-30 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0003_notifyresult"),
    ]

    operations = [
        migrations.CreateModel(
            name="OperatorLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("operator", models.CharField(default="admin", help_text="操作人", max_length=64)),
                (
                    "action",
                    models.CharField(
                        choices=[("add", "添加"), ("modify", "修改"), ("delete", "删除"), ("execute", "执行")],
                        help_text="操作类型",
                        max_length=32,
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[("event", "事件"), ("alert", "告警"), ("incident", "事故"), ("system", "系统")],
                        default="system",
                        help_text="目标类型",
                        max_length=32,
                    ),
                ),
                ("operator_object", models.CharField(blank=True, help_text="操作对象", max_length=100, null=True)),
                ("target_id", models.CharField(blank=True, help_text="目标ID", max_length=100, null=True)),
                ("overview", models.TextField(blank=True, help_text="操作概述", null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, help_text="Created Time")),
            ],
            options={"verbose_name": "操作日志", "verbose_name_plural": "操作日志", "db_table": "alerts_operator_log",},
        ),
    ]
