# Generated by Django 4.2.7 on 2025-06-18 03:05

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alerts", "0003_alertassignment_alertshield_alertremindertask"),
    ]

    operations = [
        migrations.CreateModel(
            name="Incident",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_by", models.CharField(default="", max_length=32, verbose_name="Creator")),
                ("updated_by", models.CharField(default="", max_length=32, verbose_name="Updater")),
                ("incident_id", models.CharField(db_index=True, help_text="事故ID", max_length=100, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待响应"),
                            ("processing", "处理中"),
                            ("resolved", "已处理"),
                            ("closed", "已关闭"),
                            ("unassigned", "未分派"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="事件状态",
                        max_length=32,
                    ),
                ),
                ("level", models.CharField(db_index=True, help_text="级别", max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, help_text="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True, help_text="更新时间")),
                ("title", models.CharField(help_text="标题", max_length=256)),
                ("content", models.TextField(blank=True, help_text="内容", null=True)),
                ("note", models.TextField(blank=True, help_text="事件备注", null=True)),
                ("labels", models.JSONField(default=dict, help_text="标签")),
                (
                    "operate",
                    models.CharField(
                        blank=True,
                        choices=[("acknowledge", "认领"), ("close", "关闭"), ("reassign", "转派"), ("assign", "分派")],
                        help_text="操作",
                        max_length=64,
                        null=True,
                    ),
                ),
                ("operator", models.JSONField(blank=True, default=list, help_text="处理人")),
                (
                    "fingerprint",
                    models.CharField(blank=True, db_index=True, help_text="事件指纹", max_length=32, null=True),
                ),
                ("alert", models.ManyToManyField(to="alerts.alert")),
            ],
            options={
                "db_table": "alerts_incident",
                "ordering": ["-updated_at"],
                "indexes": [
                    django.contrib.postgres.indexes.BTreeIndex(fields=["created_at"], name="incident_created_btree"),
                    django.contrib.postgres.indexes.GinIndex(fields=["operator"], name="incident_operator_gin"),
                ],
            },
        ),
    ]
