# Generated by Django 4.2.7 on 2025-06-24 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0004_incident"),
    ]

    operations = [
        migrations.CreateModel(
            name="AggregationRules",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created Time")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated Time")),
                ("created_by", models.CharField(default="", max_length=32, verbose_name="Creator")),
                ("updated_by", models.CharField(default="", max_length=32, verbose_name="Updater")),
                ("rule_id", models.CharField(db_index=True, help_text="规则ID", max_length=100, unique=True)),
                ("name", models.CharField(help_text="规则名称", max_length=100)),
                ("description", models.TextField(blank=True, help_text="规则描述", null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True, help_text="是否启用")),
                ("template_title", models.CharField(blank=True, help_text="模板标题", max_length=200, null=True)),
                ("template_content", models.TextField(blank=True, help_text="模板内容", null=True)),
                ("severity", models.CharField(default="warning", help_text="严重程度", max_length=32)),
                ("condition", models.JSONField(default=list, help_text="规则条件配置")),
                (
                    "type",
                    models.CharField(
                        choices=[("alert", "告警"), ("incident", "事故")], default="alert", help_text="聚合类型", max_length=32
                    ),
                ),
            ],
            options={"verbose_name": "聚合规则", "verbose_name_plural": "聚合规则", "db_table": "alerts_aggregation_rules",},
        ),
        migrations.AlterModelOptions(name="incident", options={},),
        migrations.AlterField(
            model_name="incident",
            name="status",
            field=models.CharField(
                choices=[("pending", "待响应"), ("processing", "处理中"), ("resolved", "已处理"), ("closed", "已关闭")],
                db_index=True,
                default="pending",
                help_text="事件状态",
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="CorrelationRules",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created Time")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated Time")),
                ("created_by", models.CharField(default="", max_length=32, verbose_name="Creator")),
                ("updated_by", models.CharField(default="", max_length=32, verbose_name="Updater")),
                ("name", models.CharField(help_text="关联规则名称", max_length=100, unique=True)),
                (
                    "scope",
                    models.CharField(choices=[("all", "全部匹配"), ("filter", "过滤匹配")], help_text="作用范围", max_length=20),
                ),
                (
                    "rule_type",
                    models.CharField(choices=[("alert", "告警"), ("event", "事件")], help_text="规则类型", max_length=20),
                ),
                ("description", models.TextField(blank=True, null=True, verbose_name="描述")),
                (
                    "aggregation_rules",
                    models.ManyToManyField(
                        help_text="关联的聚合规则", related_name="correlation_rules", to="alerts.aggregationrules"
                    ),
                ),
            ],
            options={"verbose_name": "关联规则", "verbose_name_plural": "关联规则", "db_table": "alerts_correlation_rules",},
        ),
    ]
