# Generated by Django 4.2.7 on 2025-07-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0005_sessioneventrelation_aggregationrules_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="correlationrules",
            name="exec_time",
            field=models.DateTimeField(blank=True, help_text="规则执行时间", null=True),
        ),
        migrations.AddField(
            model_name="correlationrules",
            name="close_time",
            field=models.CharField(blank=True, help_text="自动关闭时间", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="alert",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待响应"),
                    ("processing", "处理中"),
                    ("resolved", "已处理"),
                    ("closed", "已关闭"),
                    ("unassigned", "未分派"),
                    ("auto_close", "自动关闭"),
                ],
                db_index=True,
                default="unassigned",
                help_text="告警状态",
                max_length=32,
            ),
        ),
    ]
