networks:
  prod:

services:
  web:
    image: ${DOCKER_IMAGE_WEB}
    restart: always
    environment:
      NEXTAUTH_URL: http://${HOST_IP}:${TRAEFIK_WEB_PORT}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXTAPI_URL: http://server:8000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.system-manager-web.rule=Host(`${HOST_IP}`)"
      - "traefik.http.routers.system-manager-web.entrypoints=web"
      - "traefik.http.services.system-manager-web.loadbalancer.server.port=3000"
    networks:
      - prod
    depends_on:
      server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "node", "-e", "fetch('http://web:3000/healthcheck').then(res => res.status === 200)"]
      start_period: 5s