# Generated by Django 4.2.22 on 2025-08-05 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mlops', '0001_initial'),
        ('playground', '0002_playgroundfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playgroundfile',
            name='capability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='mlops.anomalydetectionserving', verbose_name='能力演示ID'),
        ),
    ]
