# Generated by Django 4.2.22 on 2025-08-05 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_alter_playgroundfile_capability'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playgroundfile',
            old_name='capability',
            new_name='serving',
        ),
    ]
