# Generated by Django 4.2.22 on 2025-08-06 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0004_rename_capability_playgroundfile_serving'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playgroundfile',
            name='serving',
            field=models.IntegerField(verbose_name='能力演示ID'),
        ),
    ]
