# Generated by Django 4.2.22 on 2025-08-06 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0005_alter_playgroundfile_serving'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaygroundAnomalyDetectionExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='Creator')),
                ('updated_by', models.CharField(default='', max_length=32, verbose_name='Updater')),
                ('domain', models.CharField(default='domain.com', max_length=100, verbose_name='Domain')),
                ('updated_by_domain', models.CharField(default='domain.com', max_length=100, verbose_name='updated by domain')),
                ('capability', models.IntegerField(verbose_name='能力演示ID')),
                ('name', models.CharField(max_length=255, verbose_name='文件名称')),
                ('train_data', models.JSONField(help_text='训练数据，包含timestamp和value', verbose_name='文件数据')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '能力演示文件',
                'verbose_name_plural': '能力演示文件',
            },
        ),
        migrations.DeleteModel(
            name='PlayGroundFile',
        ),
    ]
