# Generated by Django 4.2.22 on 2025-08-07 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0007_alter_playgroundcategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playgroundcategory',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
