const sidebars = {
  tutorialSidebar: [{type: 'autogenerated', dirName: 'products'}],
  deploySidebar: [{type: 'autogenerated', dirName: 'deploy'}],
  operationsSidebar: [{type: 'autogenerated', dirName: 'operations'}],
  faqSidebar: [{type: 'autogenerated', dirName: 'faq'}],
  assertsSidebar: [{type: 'autogenerated', dirName: 'asserts'}],
  devSidebar: [{type: 'autogenerated', dirName: 'dev'}],
};

export default sidebars;
