# Generated by Django 4.2.7 on 2025-05-28 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_collectconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorobject',
            name='icon',
            field=models.CharField(default='', max_length=100, verbose_name='监控对象图标'),
        ),
    ]
