# Generated by Django 4.2.15 on 2025-06-17 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_monitorobject_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorObjectOrganizationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='Creator')),
                ('updated_by', models.CharField(default='', max_length=32, verbose_name='Updater')),
                ('name', models.CharField(max_length=100, verbose_name='分组规则名称')),
                ('organizations', models.JSONField(default=list, verbose_name='所属组织')),
                ('rule', models.JSONField(default=dict, verbose_name='分组规则详情')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('monitor_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.monitorobject', verbose_name='监控对象')),
            ],
            options={
                'verbose_name': 'Time Fields',
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='MonitorInstanceGroupingRule',
        ),
    ]
