# Generated by Django 4.2.15 on 2025-06-18 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_monitorobjectorganizationrule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorevent',
            name='event_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='事件发生时间'),
        ),
        migrations.AddField(
            model_name='monitorpolicy',
            name='enable_alerts',
            field=models.JSONField(default=list, verbose_name='启用的告警类型'),
        ),
    ]
