# Generated by Django 4.2.15 on 2025-06-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_monitorevent_event_time_monitorpolicy_enable_alerts'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectconfig',
            name='domain',
            field=models.CharField(default='domain.com', max_length=100, verbose_name='Domain'),
        ),
        migrations.AddField(
            model_name='collectconfig',
            name='updated_by_domain',
            field=models.CharField(default='domain.com', max_length=100, verbose_name='updated by domain'),
        ),
        migrations.AddField(
            model_name='metric',
            name='domain',
            field=models.CharField(default='domain.com', max_length=100, verbose_name='Domain'),
        ),
        migrations.AddField(
            model_name='metric',
            name='updated_by_domain',
            field=models.CharField(default='domain.com', max_length=100, verbose_name='updated by domain'),
        ),
        migrations.AddField(
            model_name='metricgroup',
            name='domain',
            field=models.CharField(default='domain.com', max_length=100, verbose_name='Domain'),
        ),
        migrations.AddField(
            model_name='metricgroup',
            name='updated_by_domain',
            field=models.CharField(default='domain.com', max_length=100, verbose_name='updated by domain'),
        ),
        migrations.AddField(
            model_name='monitorinstance',
            name='domain',
            field=models.CharField(default='domain.com', max_length=100, verbose_name='Domain'),
        ),
        migrations.AddField(
            model_name='monitorinstance',
            name='updated_by_domain',
            field=models.CharField(default='domain.com', max_length=100, verbose_name='updated by domain'),
        ),
        migrations.AddField(
            model_name='monitorinstanceorganization',
            name='domain',
            field=models.CharField(default='domain.com', max_length=100, verbose_name='Domain'),
        ),
        migrations.AddField(
            model_name='monitorinstanceorganization',
            name='updated_by_domain',
            field=models.CharField(default='domain.com', max_length=100, verbose_name='updated by domain'),
        ),
        migrations.AddField(
            model_name='monitorobject',
            name='domain',
            field=models.CharField(default='domain.com', max_length=100, verbose_name='Domain'),
        ),
        migrations.AddField(
            model_name='monitorobject',
            name='updated_by_domain',
            field=models.CharField(default='domain.com', max_length=100, verbose_name='updated by domain'),
        ),
        migrations.AddField(
            model_name='monitorobjectorganizationrule',
            name='domain',
            field=models.CharField(default='domain.com', max_length=100, verbose_name='Domain'),
        ),
        migrations.AddField(
            model_name='monitorobjectorganizationrule',
            name='updated_by_domain',
            field=models.CharField(default='domain.com', max_length=100, verbose_name='updated by domain'),
        ),
        migrations.AddField(
            model_name='monitorplugin',
            name='domain',
            field=models.CharField(default='domain.com', max_length=100, verbose_name='Domain'),
        ),
        migrations.AddField(
            model_name='monitorplugin',
            name='updated_by_domain',
            field=models.CharField(default='domain.com', max_length=100, verbose_name='updated by domain'),
        ),
        migrations.AddField(
            model_name='monitorpolicy',
            name='domain',
            field=models.CharField(default='domain.com', max_length=100, verbose_name='Domain'),
        ),
        migrations.AddField(
            model_name='monitorpolicy',
            name='updated_by_domain',
            field=models.CharField(default='domain.com', max_length=100, verbose_name='updated by domain'),
        ),
        migrations.AddField(
            model_name='policyorganization',
            name='domain',
            field=models.CharField(default='domain.com', max_length=100, verbose_name='Domain'),
        ),
        migrations.AddField(
            model_name='policyorganization',
            name='updated_by_domain',
            field=models.CharField(default='domain.com', max_length=100, verbose_name='updated by domain'),
        ),
        migrations.AddField(
            model_name='setting',
            name='domain',
            field=models.CharField(default='domain.com', max_length=100, verbose_name='Domain'),
        ),
        migrations.AddField(
            model_name='setting',
            name='updated_by_domain',
            field=models.CharField(default='domain.com', max_length=100, verbose_name='updated by domain'),
        ),
    ]
