# Generated by Django 4.2.15 on 2025-06-25 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0006_collectconfig_domain_collectconfig_updated_by_domain_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('templates', models.JSONField(default=list, verbose_name='策略模板列表')),
                ('monitor_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.monitorobject', verbose_name='监控对象')),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.monitorplugin', verbose_name='监控插件')),
            ],
            options={
                'verbose_name': '监控策略模板',
                'verbose_name_plural': '监控策略模板',
                'unique_together': {('monitor_object', 'plugin')},
            },
        ),
    ]
