# Generated by Django 4.2.15 on 2025-06-26 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0007_policytemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorobject',
            name='default_metric',
            field=models.TextField(blank=True, verbose_name='默认指标'),
        ),
        migrations.AddField(
            model_name='monitorobject',
            name='instance_id_keys',
            field=models.JSONField(default=list, verbose_name='联合唯一实例ID键列表'),
        ),
        migrations.AddField(
            model_name='monitorobject',
            name='supplementary_indicators',
            field=models.JSONField(default=list, verbose_name='对象实例补充指标'),
        ),
    ]
