# Generated by Django 4.2.15 on 2025-07-31 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0008_monitorobject_default_metric_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitorinstanceorganization',
            name='organization',
            field=models.IntegerField(verbose_name='组织id'),
        ),
        migrations.AlterField(
            model_name='policyorganization',
            name='organization',
            field=models.IntegerField(verbose_name='组织id'),
        ),
    ]
