# Generated by Django 4.2.15 on 2025-09-04 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0009_alter_monitorinstanceorganization_organization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorAlertMetricSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('policy_id', models.IntegerField(db_index=True, verbose_name='监控策略ID')),
                ('monitor_instance_id', models.CharField(db_index=True, max_length=100, verbose_name='监控对象实例ID')),
                ('snapshot_time', models.DateTimeField(db_index=True, verbose_name='快照时间')),
                ('raw_data', models.JSONField(default=list, verbose_name='原始指标数据')),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.monitoralert', verbose_name='关联告警')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitor.monitorevent', verbose_name='关联事件')),
            ],
            options={
                'verbose_name': '告警指标快照',
                'verbose_name_plural': '告警指标快照',
                'indexes': [models.Index(fields=['alert', 'snapshot_time'], name='monitor_mon_alert_i_117b30_idx')],
            },
        ),
    ]
