# Generated by Django 4.2.15 on 2025-09-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0010_monitoralertmetricsnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorobjectorganizationrule',
            name='monitor_instance_id',
            field=models.CharField(db_index=True, default='', max_length=200, verbose_name='关联监控对象实例ID'),
        ),
    ]
