# Generated by Django 4.2.15 on 2025-06-25 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('mlops', '0001_initial'), ('mlops', '0002_anomalydetectiontraindata_anomaly_point_count')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyDetectionDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='Creator')),
                ('updated_by', models.CharField(default='', max_length=32, verbose_name='Updater')),
                ('domain', models.CharField(default='domain.com', max_length=100, verbose_name='Domain')),
                ('updated_by_domain', models.CharField(default='domain.com', max_length=100, verbose_name='updated by domain')),
                ('name', models.CharField(max_length=100, verbose_name='数据集名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='数据集描述')),
            ],
            options={
                'verbose_name': '异常检测数据集',
                'verbose_name_plural': '异常检测数据集',
            },
        ),
        migrations.CreateModel(
            name='AnomalyDetectionTrainData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='Creator')),
                ('updated_by', models.CharField(default='', max_length=32, verbose_name='Updater')),
                ('domain', models.CharField(default='domain.com', max_length=100, verbose_name='Domain')),
                ('updated_by_domain', models.CharField(default='domain.com', max_length=100, verbose_name='updated by domain')),
                ('name', models.CharField(max_length=100, verbose_name='训练数据名称')),
                ('train_data', models.JSONField(help_text='存储训练数据', verbose_name='训练数据')),
                ('metadata', models.JSONField(blank=True, help_text='训练数据元信息', null=True, verbose_name='元数据')),
                ('is_train_data', models.BooleanField(default=False, help_text='是否为训练数据', verbose_name='是否为训练数据')),
                ('is_val_data', models.BooleanField(default=False, help_text='是否为验证数据', verbose_name='是否为验证数据')),
                ('is_test_data', models.BooleanField(default=False, help_text='是否为测试数据', verbose_name='是否为测试数据')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train_data', to='mlops.anomalydetectiondataset', verbose_name='数据集')),
                ('anomaly_point_count', models.PositiveIntegerField(default=0, help_text='异常点的数量', verbose_name='异常点数量')),
            ],
            options={
                'verbose_name': '异常检测训练数据',
                'verbose_name_plural': '异常检测训练数据',
            },
        ),
    ]
