# Generated by Django 4.2.15 on 2025-06-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomalydetectiontraindata',
            name='anomaly_point_count',
            field=models.PositiveIntegerField(default=0, help_text='异常点的数量', verbose_name='异常点数量'),
        ),
    ]
