# Generated by Django 4.2.15 on 2025-06-28 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mlops', '0002_anomalydetectiontraindata_anomaly_point_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPointFeaturesInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('windows_low', models.IntegerField(default=5, help_text='超参检索最小窗口大小', verbose_name='超参检索最小窗口大小')),
                ('windows_high', models.IntegerField(default=50, help_text='超参检索最大窗口大小', verbose_name='超参检索最大窗口大小')),
                ('enable_rolling_mean_feature', models.BooleanField(default=True, help_text='是否启用滚动平均特征', verbose_name='启用滚动平均特征')),
                ('enable_rolling_std_feature', models.BooleanField(default=True, help_text='是否启用滚动标准差特征', verbose_name='启用滚动标准差特征')),
                ('enable_rolling_min_feature', models.BooleanField(default=True, help_text='是否启用滚动最小值特征', verbose_name='启用滚动最小值特征')),
                ('enable_rolling_max_feature', models.BooleanField(default=True, help_text='是否启用滚动最大值特征', verbose_name='启用滚动最大值特征')),
                ('enable_rolling_median_feature', models.BooleanField(default=True, help_text='是否启用滚动中位数特征', verbose_name='启用滚动中位数特征')),
                ('enable_diff_1_feature', models.BooleanField(default=True, help_text='是否启用一阶差分特征', verbose_name='启用一阶差分特征')),
                ('enable_diff_2_feature', models.BooleanField(default=True, help_text='是否启用二阶差分特征', verbose_name='启用二阶差分特征')),
                ('enable_zscore_feature', models.BooleanField(default=True, help_text='是否启用Z-score特征', verbose_name='启用Z-score特征')),
                ('enable_trend_feature', models.BooleanField(default=True, help_text='是否启用趋势特征', verbose_name='启用趋势特征')),
                ('enable_autocorr_1_feature', models.BooleanField(default=True, help_text='是否启用一阶自相关特征', verbose_name='启用一阶自相关特征')),
                ('enable_hour_feature', models.BooleanField(default=True, help_text='是否启用小时特征', verbose_name='启用小时特征')),
                ('enable_minute_feature', models.BooleanField(default=True, help_text='是否启用分钟特征', verbose_name='启用分钟特征')),
                ('enable_dayofweek_feature', models.BooleanField(default=True, help_text='是否启用星期几特征', verbose_name='启用星期几特征')),
                ('enable_month_feature', models.BooleanField(default=True, help_text='是否启用月份特征', verbose_name='启用月份特征')),
                ('enable_is_weekend_feature', models.BooleanField(default=True, help_text='是否启用是否周末特征', verbose_name='启用是否周末特征')),
            ],
        ),
        migrations.CreateModel(
            name='AnomalyDetectionTrainJob',
            fields=[
                ('datapointfeaturesinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mlops.datapointfeaturesinfo')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='Creator')),
                ('updated_by', models.CharField(default='', max_length=32, verbose_name='Updater')),
                ('domain', models.CharField(default='domain.com', max_length=100, verbose_name='Domain')),
                ('updated_by_domain', models.CharField(default='domain.com', max_length=100, verbose_name='updated by domain')),
                ('name', models.CharField(max_length=100, verbose_name='任务名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='任务描述')),
                ('status', models.CharField(choices=[('pending', '待训练'), ('running', '训练中'), ('completed', '已完成'), ('failed', '训练失败')], default='pending', help_text='训练任务的当前状态', max_length=20, verbose_name='任务状态')),
                ('algorithm', models.CharField(choices=[('RandomForest', '随机森林')], help_text='使用的异常检测算法模型', max_length=50, verbose_name='算法模型')),
                ('hyperopt_config', models.JSONField(default={}, help_text='用于超参数优化的配置参数', verbose_name='超参数优化配置')),
                ('test_data_id', models.ForeignKey(help_text='关联的异常检测测试数据集', on_delete=django.db.models.deletion.CASCADE, related_name='test_jobs', to='mlops.anomalydetectiondataset', verbose_name='测试数据集')),
                ('train_data_id', models.ForeignKey(help_text='关联的异常检测训练数据集', on_delete=django.db.models.deletion.CASCADE, related_name='train_jobs', to='mlops.anomalydetectiondataset', verbose_name='训练数据集')),
                ('val_data_id', models.ForeignKey(help_text='关联的异常检测验证数据集', on_delete=django.db.models.deletion.CASCADE, related_name='val_jobs', to='mlops.anomalydetectiondataset', verbose_name='验证数据集')),
            ],
            options={
                'verbose_name': '异常检测训练任务',
                'verbose_name_plural': '异常检测训练任务',
            },
            bases=('mlops.datapointfeaturesinfo', models.Model),
        ),
    ]
