# Generated by Django 4.2.22 on 2025-08-14 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mlops', '0003_rasaintent'),
    ]

    operations = [
        migrations.CreateModel(
            name='RasaResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='Creator')),
                ('updated_by', models.CharField(default='', max_length=32, verbose_name='Updater')),
                ('domain', models.CharField(default='domain.com', max_length=100, verbose_name='Domain')),
                ('updated_by_domain', models.CharField(default='domain.com', max_length=100, verbose_name='updated by domain')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='响应名称')),
                ('example', models.JSONField(default=list, verbose_name='响应示例')),
                ('example_count', models.IntegerField(default=0, verbose_name='响应示例数量')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='mlops.rasadatasets', verbose_name='数据集')),
            ],
            options={
                'verbose_name': 'rasa响应',
                'verbose_name_plural': 'rasa响应',
            },
        ),
    ]
