# Generated by Django 4.2.15 on 2025-06-28 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mlops', '0003_datapointfeaturesinfo_anomalydetectiontrainjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anomalydetectiontrainjob',
            name='hyperopt_config',
            field=models.JSONField(default=dict, help_text='用于超参数优化的配置参数', verbose_name='超参数优化配置'),
        ),
        migrations.AlterField(
            model_name='anomalydetectiontrainjob',
            name='test_data_id',
            field=models.ForeignKey(help_text='关联的异常检测测试数据集', on_delete=django.db.models.deletion.CASCADE, related_name='test_jobs', to='mlops.anomalydetectiontraindata', verbose_name='测试数据集'),
        ),
        migrations.AlterField(
            model_name='anomalydetectiontrainjob',
            name='train_data_id',
            field=models.ForeignKey(help_text='关联的异常检测训练数据集', on_delete=django.db.models.deletion.CASCADE, related_name='train_jobs', to='mlops.anomalydetectiontraindata', verbose_name='训练数据集'),
        ),
        migrations.AlterField(
            model_name='anomalydetectiontrainjob',
            name='val_data_id',
            field=models.ForeignKey(help_text='关联的异常检测验证数据集', on_delete=django.db.models.deletion.CASCADE, related_name='val_jobs', to='mlops.anomalydetectiontraindata', verbose_name='验证数据集'),
        ),
    ]
