# Generated by Django 4.2.15 on 2025-06-28 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlops', '0004_alter_anomalydetectiontrainjob_hyperopt_config_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datapointfeaturesinfo',
            name='windows_high',
        ),
        migrations.RemoveField(
            model_name='datapointfeaturesinfo',
            name='windows_low',
        ),
        migrations.AddField(
            model_name='datapointfeaturesinfo',
            name='windows_size',
            field=models.IntegerField(default=30, help_text='滚动窗口大小', verbose_name=''),
        ),
    ]
