# Generated by Django 4.2.22 on 2025-08-14 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mlops', '0004_rasaresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='RasaRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='Creator')),
                ('updated_by', models.CharField(default='', max_length=32, verbose_name='Updater')),
                ('domain', models.CharField(default='domain.com', max_length=100, verbose_name='Domain')),
                ('updated_by_domain', models.CharField(default='domain.com', max_length=100, verbose_name='updated by domain')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='规则名称')),
                ('steps', models.JSONField(default=dict, verbose_name='规则步骤')),
                ('intent_count', models.IntegerField(default=0, verbose_name='意图数量')),
                ('response_count', models.IntegerField(default=0, verbose_name='响应数量')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='mlops.rasadatasets', verbose_name='数据集')),
            ],
            options={
                'verbose_name': 'rasa规则',
                'verbose_name_plural': 'rasa规则',
            },
        ),
    ]
