# Generated by Django 4.2.22 on 2025-08-14 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlops', '0005_rasarule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rasarule',
            name='steps',
            field=models.JSONField(default=list, verbose_name='规则步骤'),
        ),
    ]
