# Generated by Django 4.2.15 on 2025-06-28 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mlops', '0006_anomalydetectiontrainjob_max_evals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datapointfeaturesinfo',
            name='enable_autocorr_1_feature',
        ),
        migrations.RemoveField(
            model_name='datapointfeaturesinfo',
            name='enable_dayofweek_feature',
        ),
        migrations.RemoveField(
            model_name='datapointfeaturesinfo',
            name='enable_diff_1_feature',
        ),
        migrations.RemoveField(
            model_name='datapointfeaturesinfo',
            name='enable_diff_2_feature',
        ),
        migrations.RemoveField(
            model_name='datapointfeaturesinfo',
            name='enable_hour_feature',
        ),
        migrations.RemoveField(
            model_name='datapointfeaturesinfo',
            name='enable_is_weekend_feature',
        ),
        migrations.RemoveField(
            model_name='datapointfeaturesinfo',
            name='enable_minute_feature',
        ),
        migrations.RemoveField(
            model_name='datapointfeaturesinfo',
            name='enable_month_feature',
        ),
        migrations.RemoveField(
            model_name='datapointfeaturesinfo',
            name='enable_rolling_max_feature',
        ),
        migrations.RemoveField(
            model_name='datapointfeaturesinfo',
            name='enable_rolling_mean_feature',
        ),
        migrations.RemoveField(
            model_name='datapointfeaturesinfo',
            name='enable_rolling_median_feature',
        ),
        migrations.RemoveField(
            model_name='datapointfeaturesinfo',
            name='enable_rolling_min_feature',
        ),
        migrations.RemoveField(
            model_name='datapointfeaturesinfo',
            name='enable_rolling_std_feature',
        ),
        migrations.RemoveField(
            model_name='datapointfeaturesinfo',
            name='enable_trend_feature',
        ),
        migrations.RemoveField(
            model_name='datapointfeaturesinfo',
            name='enable_zscore_feature',
        ),
    ]
