# Generated by Django 4.2.22 on 2025-08-18 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mlops', '0007_rasastory'),
    ]

    operations = [
        migrations.CreateModel(
            name='RasaEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='Creator')),
                ('updated_by', models.CharField(default='', max_length=32, verbose_name='Updater')),
                ('domain', models.CharField(default='domain.com', max_length=100, verbose_name='Domain')),
                ('updated_by_domain', models.CharField(default='domain.com', max_length=100, verbose_name='updated by domain')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='实体名称')),
                ('entity_type', models.CharField(choices=[('Text', '自由标注'), ('Lookup', '枚举表')], default='Text', max_length=20, verbose_name='类型')),
                ('example', models.JSONField(default=list, help_text='实体的具体取值列表', verbose_name='实体值')),
                ('example_count', models.IntegerField(default=0, verbose_name='样例数量')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='mlops.rasadatasets', verbose_name='数据集')),
            ],
            options={
                'verbose_name': '实体',
                'verbose_name_plural': '实体',
            },
        ),
    ]
