# Generated by Django 4.2.22 on 2025-08-19 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mlops', '0008_rasaentity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rasaentity',
            name='example_count',
        ),
    ]
