# Generated by Django 4.2.22 on 2025-08-19 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mlops', '0009_remove_rasaentity_example_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rasaintent',
            name='example_count',
        ),
        migrations.RemoveField(
            model_name='rasaresponse',
            name='example_count',
        ),
    ]
