# Generated by Django 4.2.22 on 2025-08-19 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mlops', '0010_remove_rasaintent_example_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RasaSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='Creator')),
                ('updated_by', models.CharField(default='', max_length=32, verbose_name='Updater')),
                ('domain', models.CharField(default='domain.com', max_length=100, verbose_name='Domain')),
                ('updated_by_domain', models.CharField(default='domain.com', max_length=100, verbose_name='updated by domain')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='槽位名称')),
                ('solt_type', models.CharField(choices=[('Text', '记录普通文本'), ('Categorical', '记录分类类别，枚举'), ('Float', '记录数值'), ('Bool', '记录布尔值'), ('List', '记录数值列表')], default='Text', max_length=20, verbose_name='槽位类型')),
                ('is_apply', models.BooleanField(default=False, verbose_name='是否应用')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='mlops.rasadatasets', verbose_name='数据集')),
            ],
            options={
                'verbose_name': '槽位',
                'verbose_name_plural': '槽位',
            },
        ),
    ]
