# Generated by Django 4.2.22 on 2025-08-19 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mlops', '0011_rasaslot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rasaslot',
            old_name='solt_type',
            new_name='slot_type',
        ),
    ]
