# Generated by Django 4.2.22 on 2025-08-20 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlops', '0012_rename_solt_type_rasaslot_slot_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rasaslot',
            name='slot_type',
            field=models.CharField(choices=[('text', '记录普通文本'), ('categorical', '记录分类类别，枚举'), ('float', '记录数值'), ('bool', '记录布尔值'), ('list', '记录数值列表'), ('int', '记录整数')], default='text', max_length=20, verbose_name='槽位类型'),
        ),
    ]
