# Generated by Django 4.2.22 on 2025-08-20 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlops', '0013_alter_rasaslot_slot_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='rasaslot',
            name='values',
            field=models.JSONField(default=list, verbose_name='槽位值'),
        ),
    ]
