# Generated by Django 4.2.22 on 2025-08-21 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlops', '0014_rasaslot_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rasaslot',
            name='slot_type',
            field=models.CharField(choices=[('text', '记录普通文本'), ('categorical', '记录分类类别，枚举'), ('float', '记录数值'), ('bool', '记录布尔值'), ('list', '记录数值列表')], default='text', max_length=20, verbose_name='槽位类型'),
        ),
        migrations.AlterField(
            model_name='rasaslot',
            name='values',
            field=models.JSONField(default=list, help_text='type为category时选择填充此项', verbose_name='槽位值'),
        ),
    ]
