# Generated by Django 4.2.22 on 2025-08-28 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mlops', '0016_rasaform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rasastory',
            name='intent_count',
        ),
        migrations.RemoveField(
            model_name='rasastory',
            name='response_count',
        ),
    ]
