# Generated by Django 4.2.22 on 2025-08-28 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mlops', '0017_remove_rasastory_intent_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rasarule',
            name='intent_count',
        ),
        migrations.RemoveField(
            model_name='rasarule',
            name='response_count',
        ),
    ]
