# Generated by Django 4.2.22 on 2025-09-05 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlops', '0019_rasaaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='RasaPipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='Creator')),
                ('updated_by', models.CharField(default='', max_length=32, verbose_name='Updater')),
                ('domain', models.CharField(default='domain.com', max_length=100, verbose_name='Domain')),
                ('updated_by_domain', models.CharField(default='domain.com', max_length=100, verbose_name='updated by domain')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='管道名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='管道描述')),
                ('config', models.JSONField(default=dict, help_text='Rasa pipeline配置，包含tokenizer、featurizer、classifier等组件', verbose_name='管道配置')),
                ('datasets', models.ManyToManyField(blank=True, help_text='该管道关联的训练数据集', related_name='pipelines', to='mlops.rasadatasets', verbose_name='关联数据集')),
            ],
            options={
                'verbose_name': 'Rasa训练管道',
                'verbose_name_plural': 'Rasa训练管道',
            },
        ),
    ]
