# Generated by Django 4.2.22 on 2025-09-15 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mlops', '0021_logclusteringdataset_logclusteringtraindata_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeseriespredicttrainhistory',
            options={'verbose_name': '时间序列预测训练历史', 'verbose_name_plural': '时间序列预测训练历史'},
        ),
        migrations.AlterModelOptions(
            name='timeseriespredicttrainjob',
            options={'verbose_name': '时间序列预测训练任务', 'verbose_name_plural': '时间序列预测训练任务'},
        ),
        migrations.AlterField(
            model_name='timeseriespredicttrainhistory',
            name='test_data_id',
            field=models.ForeignKey(help_text='关联的时间序列预测测试数据集', on_delete=django.db.models.deletion.CASCADE, related_name='test_history', to='mlops.timeseriespredicttraindata', verbose_name='测试数据集'),
        ),
        migrations.AlterField(
            model_name='timeseriespredicttrainhistory',
            name='train_data_id',
            field=models.ForeignKey(help_text='关联的时间序列预测训练数据集', on_delete=django.db.models.deletion.CASCADE, related_name='train_history', to='mlops.timeseriespredicttraindata', verbose_name='训练数据集'),
        ),
        migrations.AlterField(
            model_name='timeseriespredicttrainhistory',
            name='val_data_id',
            field=models.ForeignKey(help_text='关联的时间序列预测验证数据集', on_delete=django.db.models.deletion.CASCADE, related_name='val_history', to='mlops.timeseriespredicttraindata', verbose_name='验证数据集'),
        ),
    ]
