# Generated by Django 4.2.22 on 2025-10-07 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mlops', '0022_alter_timeseriespredicttrainhistory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyDetectionTrainHistory',
            fields=[
                ('datapointfeaturesinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mlops.datapointfeaturesinfo')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='Creator')),
                ('updated_by', models.CharField(default='', max_length=32, verbose_name='Updater')),
                ('domain', models.CharField(default='domain.com', max_length=100, verbose_name='Domain')),
                ('updated_by_domain', models.CharField(default='domain.com', max_length=100, verbose_name='updated by domain')),
                ('algorithm', models.CharField(choices=[('RandomForest', '随机森林')], help_text='使用的异常检测算法模型', max_length=50, verbose_name='算法模型')),
                ('hyperopt_config', models.JSONField(default=dict, help_text='用于超参数优化的配置参数', verbose_name='超参数优化配置')),
                ('status', models.CharField(choices=[('running', '训练中'), ('completed', '已完成'), ('failed', '训练失败')], default='pending', help_text='训练任务的当前状态', max_length=20, verbose_name='任务状态')),
                ('test_data_id', models.ForeignKey(help_text='关联的异常检测测试数据集', on_delete=django.db.models.deletion.CASCADE, related_name='test_history', to='mlops.anomalydetectiontraindata', verbose_name='测试数据集')),
                ('train_data_id', models.ForeignKey(help_text='关联的异常检测训练数据集', on_delete=django.db.models.deletion.CASCADE, related_name='train_history', to='mlops.anomalydetectiontraindata', verbose_name='训练数据集')),
                ('val_data_id', models.ForeignKey(help_text='关联的异常检测验证数据集', on_delete=django.db.models.deletion.CASCADE, related_name='val_history', to='mlops.anomalydetectiontraindata', verbose_name='验证数据集')),
            ],
            options={
                'verbose_name': '异常检测训练历史',
                'verbose_name_plural': '异常检测训练历史',
            },
            bases=('mlops.datapointfeaturesinfo', models.Model),
        ),
    ]
