# Generated by Django 4.2.15 on 2025-06-06 03:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opspilot", "0004_knowledgetask_knowledge_base_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="ocrprovider",
            name="is_build_in",
            field=models.BooleanField(default=True, verbose_name="是否内置"),
        ),
        migrations.AlterField(
            model_name="embedprovider",
            name="name",
            field=models.CharField(max_length=255, verbose_name="名称"),
        ),
        migrations.AlterField(
            model_name="ocrprovider",
            name="name",
            field=models.CharField(max_length=255, verbose_name="名称"),
        ),
        migrations.AlterField(
            model_name="rerankprovider",
            name="name",
            field=models.CharField(max_length=255, verbose_name="名称"),
        ),
    ]
