# Generated by Django 4.2.15 on 2025-06-23 02:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opspilot", "0005_ocrprovider_is_build_in"),
    ]

    operations = [
        migrations.AddField(
            model_name="bot",
            name="domain",
            field=models.CharField(default="domain.com", max_length=100, verbose_name="Domain"),
        ),
        migrations.AddField(
            model_name="botconversationhistory",
            name="domain",
            field=models.CharField(default="domain.com", max_length=100, verbose_name="Domain"),
        ),
        migrations.AddField(
            model_name="channel",
            name="domain",
            field=models.CharField(default="domain.com", max_length=100, verbose_name="Domain"),
        ),
        migrations.AddField(
            model_name="knowledgebase",
            name="domain",
            field=models.CharField(default="domain.com", max_length=100, verbose_name="Domain"),
        ),
        migrations.AddField(
            model_name="knowledgedocument",
            name="domain",
            field=models.CharField(default="domain.com", max_length=100, verbose_name="Domain"),
        ),
        migrations.AddField(
            model_name="knowledgetask",
            name="domain",
            field=models.CharField(default="domain.com", max_length=100, verbose_name="Domain"),
        ),
        migrations.AddField(
            model_name="llmskill",
            name="domain",
            field=models.CharField(default="domain.com", max_length=100, verbose_name="Domain"),
        ),
        migrations.AddField(
            model_name="rasamodel",
            name="domain",
            field=models.CharField(default="domain.com", max_length=100, verbose_name="Domain"),
        ),
        migrations.AddField(
            model_name="skillrule",
            name="domain",
            field=models.CharField(default="domain.com", max_length=100, verbose_name="Domain"),
        ),
        migrations.AddField(
            model_name="skilltools",
            name="domain",
            field=models.CharField(default="domain.com", max_length=100, verbose_name="Domain"),
        ),
        migrations.AddField(
            model_name="bot",
            name="updated_by_domain",
            field=models.CharField(default="domain.com", max_length=100, verbose_name="updated by domain"),
        ),
        migrations.AddField(
            model_name="botconversationhistory",
            name="updated_by_domain",
            field=models.CharField(default="domain.com", max_length=100, verbose_name="updated by domain"),
        ),
        migrations.AddField(
            model_name="channel",
            name="updated_by_domain",
            field=models.CharField(default="domain.com", max_length=100, verbose_name="updated by domain"),
        ),
        migrations.AddField(
            model_name="knowledgebase",
            name="updated_by_domain",
            field=models.CharField(default="domain.com", max_length=100, verbose_name="updated by domain"),
        ),
        migrations.AddField(
            model_name="knowledgedocument",
            name="updated_by_domain",
            field=models.CharField(default="domain.com", max_length=100, verbose_name="updated by domain"),
        ),
        migrations.AddField(
            model_name="llmskill",
            name="updated_by_domain",
            field=models.CharField(default="domain.com", max_length=100, verbose_name="updated by domain"),
        ),
        migrations.AddField(
            model_name="rasamodel",
            name="updated_by_domain",
            field=models.CharField(default="domain.com", max_length=100, verbose_name="updated by domain"),
        ),
        migrations.AddField(
            model_name="skillrule",
            name="updated_by_domain",
            field=models.CharField(default="domain.com", max_length=100, verbose_name="updated by domain"),
        ),
        migrations.AddField(
            model_name="skilltools",
            name="updated_by_domain",
            field=models.CharField(default="domain.com", max_length=100, verbose_name="updated by domain"),
        ),
    ]
