# Generated by Django 4.2.15 on 2025-06-24 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opspilot", "0006_bot_domain_botconversationhistory_domain_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmskill",
            name="enable_rag_strict_mode",
            field=models.BooleanField(default=False, verbose_name="启用RAG严格模式"),
        ),
        migrations.AddField(
            model_name="webpageknowledge",
            name="sync_enabled",
            field=models.BooleanField(default=False, verbose_name="Sync Enabled"),
        ),
        migrations.AddField(
            model_name="webpageknowledge",
            name="sync_time",
            field=models.CharField(blank=True, null=True, verbose_name="Sync Time"),
        ),
        migrations.CreateModel(
            name="QAPairs",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created Time")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated Time")),
                ("created_by", models.CharField(default="", max_length=32, verbose_name="Creator")),
                ("updated_by", models.CharField(default="", max_length=32, verbose_name="Updater")),
                ("domain", models.CharField(default="domain.com", max_length=100, verbose_name="Domain")),
                (
                    "updated_by_domain",
                    models.CharField(default="domain.com", max_length=100, verbose_name="updated by domain"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="问答对名称")),
                ("description", models.TextField(blank=True, null=True, verbose_name="描述")),
                ("qa_count", models.IntegerField(default=0, verbose_name="问答对数量")),
                ("document_id", models.IntegerField(default=0, verbose_name="文档ID")),
                ("document_source", models.CharField(default="file", max_length=50, verbose_name="文档来源")),
                (
                    "knowledge_base",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="opspilot.knowledgebase"),
                ),
                ("llm_model", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="opspilot.llmmodel")),
            ],
            options={
                "verbose_name": "Maintainer Fields",
                "abstract": False,
            },
        ),
    ]
