# Generated by Django 4.2.15 on 2025-07-01 03:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opspilot", "0007_llmskill_enable_rag_strict_mode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgetask",
            name="is_qa_task",
            field=models.BooleanField(default=False, verbose_name="Is QA Task"),
        ),
    ]
