# Generated by Django 4.2.15 on 2025-07-03 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opspilot", "0008_knowledgetask_is_qa_task"),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeGraph",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created Time")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated Time")),
                ("created_by", models.CharField(default="", max_length=32, verbose_name="Creator")),
                ("updated_by", models.CharField(default="", max_length=32, verbose_name="Updater")),
                ("domain", models.CharField(default="domain.com", max_length=100, verbose_name="Domain")),
                (
                    "updated_by_domain",
                    models.CharField(default="domain.com", max_length=100, verbose_name="updated by domain"),
                ),
                ("rebuild_community", models.BooleanField(default=False, verbose_name="是否重建社区")),
                ("doc_list", models.JSONField(default=list)),
                (
                    "embed_model",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="opspilot.embedprovider"
                    ),
                ),
                (
                    "knowledge_base",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="opspilot.knowledgebase"),
                ),
                ("llm_model", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="opspilot.llmmodel")),
                (
                    "rerank_model",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="opspilot.rerankprovider"
                    ),
                ),
            ],
            options={
                "verbose_name": "Maintainer Fields",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GraphChunkMap",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("chunk_id", models.CharField(max_length=255, verbose_name="Chunk ID")),
                ("graph_id", models.CharField(max_length=255, verbose_name="Graph ID")),
                (
                    "knowledge_graph",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="opspilot.knowledgegraph"),
                ),
            ],
        ),
    ]
