# Generated by Django 4.2.15 on 2025-07-09 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opspilot", "0011_rename_result_count_knowledgebase_rag_size_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmskill",
            name="enable_km_route",
            field=models.BooleanField(default=False, verbose_name="启用知识库路由"),
        ),
        migrations.AddField(
            model_name="llmskill",
            name="km_llm_model",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="km_llm_model",
                to="opspilot.llmmodel",
            ),
        ),
    ]
