# Generated by Django 4.2.15 on 2025-07-16 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opspilot", "0012_llmskill_enable_km_route_llmskill_km_llm_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qapairs",
            name="llm_model",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="opspilot.llmmodel"
            ),
        ),
    ]
