# Generated by Django 4.2.22 on 2025-07-24 06:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opspilot", "0013_alter_qapairs_llm_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmskill",
            name="guide",
            field=models.TextField(blank=True, default="", null=True, verbose_name="技能引导"),
        ),
        migrations.AlterField(
            model_name="llmskill",
            name="skill_type",
            field=models.IntegerField(
                choices=[(1, "Basic Tool"), (2, "Knowledge Tool"), (3, "Plan Execute"), (4, "Lats")],
                default=1,
                verbose_name="技能类型",
            ),
        ),
    ]
