# Generated by Django 4.2.22 on 2025-07-28 07:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opspilot", "0014_llmskill_guide_alter_llmskill_skill_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="bot",
            name="bot_type",
            field=models.IntegerField(choices=[(1, "Pilot"), (2, "LobeChat")], default=1, verbose_name="类型"),
        ),
        migrations.AddField(
            model_name="knowledgegraph",
            name="status",
            field=models.CharField(default="completed", max_length=50, verbose_name="状态"),
        ),
    ]
