# Generated by Django 4.2.22 on 2025-07-29 02:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opspilot", "0015_bot_bot_type_knowledgegraph_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="qapairs",
            name="generate_count",
            field=models.IntegerField(default=0, verbose_name="生成的数据"),
        ),
        migrations.AddField(
            model_name="qapairs",
            name="status",
            field=models.CharField(default="completed", max_length=50, verbose_name="状态"),
        ),
    ]
