# Generated by Django 4.2.22 on 2025-08-01 06:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opspilot", "0016_qapairs_generate_count_qapairs_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgetask",
            name="completed_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="knowledgetask",
            name="total_count",
            field=models.IntegerField(default=0),
        ),
    ]
