# Generated by Django 4.2.22 on 2025-08-06 03:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opspilot", "0017_knowledgetask_completed_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="qapairs",
            name="create_type",
            field=models.CharField(default="document", max_length=20),
        ),
    ]
