# Generated by Django 4.2.22 on 2025-08-13 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opspilot", "0018_qapairs_create_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, unique=True, verbose_name="模型类型名称")),
                ("display_name", models.CharField(max_length=100, verbose_name="显示名称")),
                ("icon", models.CharField(blank=True, max_length=100, null=True, verbose_name="图标")),
            ],
        ),
        migrations.AlterField(
            model_name="llmmodel",
            name="llm_model_type",
            field=models.CharField(
                choices=[
                    ("chat-gpt", "OpenAI"),
                    ("zhipu", "智谱AI"),
                    ("hugging_face", "Hugging Face"),
                    ("deep-seek", "DeepSeek"),
                    ("Baichuan", "百川"),
                ],
                max_length=255,
                verbose_name="LLM模型类型",
            ),
        ),
        migrations.AddField(
            model_name="embedprovider",
            name="model_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="opspilot.modeltype",
                verbose_name="模型类型",
            ),
        ),
        migrations.AddField(
            model_name="llmmodel",
            name="model_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="opspilot.modeltype",
                verbose_name="模型类型",
            ),
        ),
        migrations.AddField(
            model_name="ocrprovider",
            name="model_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="opspilot.modeltype",
                verbose_name="模型类型",
            ),
        ),
        migrations.AddField(
            model_name="rerankprovider",
            name="model_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="opspilot.modeltype",
                verbose_name="模型类型",
            ),
        ),
    ]
