# Generated by Django 4.2.22 on 2025-08-22 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opspilot", "0019_modeltype_alter_llmmodel_llm_model_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmmodel",
            name="label",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="标签"),
        ),
        migrations.AddField(
            model_name="modeltype",
            name="is_build_in",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="modeltype",
            name="index",
            field=models.IntegerField(default=0, verbose_name="排序"),
        ),
        migrations.AddField(
            model_name="qapairs",
            name="answer_llm_model",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answer_llm_model",
                to="opspilot.llmmodel",
            ),
        ),
        migrations.AddField(
            model_name="qapairs",
            name="answer_prompt",
            field=models.TextField(blank=True, default="", null=True, verbose_name="答案提示词"),
        ),
        migrations.AddField(
            model_name="qapairs",
            name="question_prompt",
            field=models.TextField(blank=True, default="", null=True, verbose_name="问题提示词"),
        ),
    ]
