# Generated by Django 4.2.22 on 2025-08-25 03:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("opspilot", "0020_llmmodel_label_modeltype_is_build_in_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="embedprovider",
            name="embed_model_type",
        ),
        migrations.RemoveField(
            model_name="llmmodel",
            name="llm_model_type",
        ),
        migrations.RemoveField(
            model_name="rerankprovider",
            name="rerank_model_type",
        ),
    ]
