# Generated by Django 4.2.22 on 2025-08-27 08:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opspilot", "0021_remove_embedprovider_embed_model_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="knowledgebase",
            name="enable_text_search",
        ),
        migrations.RemoveField(
            model_name="knowledgebase",
            name="enable_vector_search",
        ),
        migrations.RemoveField(
            model_name="knowledgebase",
            name="rag_num_candidates",
        ),
        migrations.RemoveField(
            model_name="knowledgebase",
            name="text_search_mode",
        ),
        migrations.RemoveField(
            model_name="knowledgebase",
            name="text_search_weight",
        ),
        migrations.RemoveField(
            model_name="knowledgebase",
            name="vector_search_weight",
        ),
        migrations.AddField(
            model_name="knowledgebase",
            name="score_threshold",
            field=models.FloatField(default=0.7, verbose_name="Score threshold"),
        ),
        migrations.AddField(
            model_name="knowledgebase",
            name="search_type",
            field=models.CharField(default="similarity_score_threshold", max_length=50, verbose_name="Search Type"),
        ),
    ]
