# Generated by Django 4.2.22 on 2025-08-27 09:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("opspilot", "0022_remove_knowledgebase_enable_text_search_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="knowledgebase",
            name="rag_k",
        ),
    ]
