# Generated by Django 4.2.22 on 2025-08-28 08:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opspilot", "0023_remove_knowledgebase_rag_k"),
    ]

    operations = [
        migrations.AddField(
            model_name="modeltype",
            name="tags",
            field=models.JSONField(default=list),
        ),
    ]
