# Generated by Django 4.2.22 on 2025-09-01 06:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opspilot", "0024_modeltype_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgebase",
            name="rag_recall_mode",
            field=models.CharField(default="chunk", max_length=20),
        ),
    ]
