# Generated by Django 4.2.22 on 2025-09-04 03:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opspilot", "0025_knowledgebase_rag_recall_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmskill",
            name="enable_suggest",
            field=models.BooleanField(default=False, verbose_name="启用建议"),
        ),
    ]
