# Generated by Django 4.2.22 on 2025-09-12 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opspilot", "0026_llmskill_enable_suggest"),
    ]

    operations = [
        migrations.CreateModel(
            name="BotWorkFlow",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("flow_json", models.JSONField(default=list, verbose_name="流程数据")),
                ("web_json", models.JSONField(default=dict, verbose_name="前端数据")),
            ],
            options={
                "verbose_name": "机器人工作流",
                "verbose_name_plural": "机器人工作流",
            },
        ),
        migrations.AlterField(
            model_name="bot",
            name="bot_type",
            field=models.IntegerField(choices=[(1, "Pilot"), (2, "LobeChat"), (3, "ChatFlow")], default=1, verbose_name="类型"),
        ),
        migrations.CreateModel(
            name="WorkFlowTaskResult",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("run_time", models.DateTimeField(auto_now_add=True, verbose_name="运行时间")),
                ("status", models.CharField(max_length=50, verbose_name="状态")),
                ("input_data", models.TextField(verbose_name="输入数据")),
                ("output_data", models.JSONField(default=dict, verbose_name="输出数据")),
                ("last_output", models.TextField(blank=True, null=True, verbose_name="最后输出")),
                ("bot_work_flow", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="opspilot.botworkflow", verbose_name="机器人工作流")),
            ],
        ),
        migrations.AddField(
            model_name="botworkflow",
            name="bot",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="opspilot.bot", verbose_name="机器人"),
        ),
    ]
