# Generated by Django 4.2.22 on 2025-09-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opspilot", "0027_botworkflow_alter_bot_bot_type_workflowtaskresult_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmskill",
            name="enable_query_rewrite",
            field=models.BooleanField(default=False, verbose_name="问题优化"),
        ),
    ]
