# Generated by Django 4.2.22 on 2025-09-23 09:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("opspilot", "0028_llmskill_enable_query_rewrite"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TeamTokenUseInfo",
        ),
        migrations.RemoveField(
            model_name="quotarule",
            name="token_set",
        ),
        migrations.RemoveField(
            model_name="llmmodel",
            name="consumer_team",
        ),
    ]
