# Generated by Django 4.2.22 on 2025-09-24 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opspilot', '0029_delete_teamtokenuseinfo_remove_quotarule_token_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowtaskresult',
            name='execute_type',
            field=models.CharField(default='restful', max_length=50),
        ),
    ]
