# Generated by Django 4.2.22 on 2025-09-26 09:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("opspilot", "0030_workflowtaskresult_execute_type"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TokenConsumption",
        ),
    ]
