# Generated by Django 4.2.22 on 2025-09-17 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfraInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='Creator')),
                ('updated_by', models.CharField(default='', max_length=32, verbose_name='Updater')),
                ('domain', models.CharField(default='domain.com', max_length=100, verbose_name='Domain')),
                ('updated_by_domain', models.CharField(default='domain.com', max_length=100, verbose_name='updated by domain')),
                ('name', models.CharField(max_length=100, verbose_name='实例名称')),
                ('status', models.CharField(choices=[('stopped', '已停止'), ('starting', '启动中'), ('running', '运行中'), ('stopping', '停止中'), ('error', '错误')], default='stopped', max_length=20, verbose_name='运行状态')),
                ('endpoint', models.CharField(blank=True, max_length=200, null=True, verbose_name='访问端点')),
                ('env_vars', models.JSONField(default=dict, help_text='容器运行时的环境变量，会覆盖镜像默认配置', verbose_name='环境变量')),
                ('command', models.JSONField(blank=True, default=list, help_text='覆盖镜像的 CMD，为空则使用镜像默认值', verbose_name='启动命令')),
                ('args', models.JSONField(blank=True, default=list, help_text='传递给启动命令的参数', verbose_name='启动参数')),
                ('port_mappings', models.JSONField(default=dict, help_text="容器端口到宿主机端口的映射，格式: {'8080': '30080'}", verbose_name='端口映射')),
                ('volume_mounts', models.JSONField(default=list, help_text="持久化卷挂载配置，格式: [{'host_path': '/data', 'container_path': '/app/data', 'read_only': false}]", verbose_name='卷挂载')),
                ('persistent_dirs', models.JSONField(default=list, help_text='需要持久化的容器内目录路径', verbose_name='持久化目录')),
                ('cpu_limit', models.CharField(blank=True, help_text="如: '1', '0.5', '2'", max_length=20, null=True, verbose_name='CPU限制')),
                ('memory_limit', models.CharField(blank=True, help_text="如: '1Gi', '512Mi'", max_length=20, null=True, verbose_name='内存限制')),
                ('extra_params', models.JSONField(default=dict, help_text='其他容器启动参数', verbose_name='额外参数')),
            ],
            options={
                'verbose_name': '基础设施实例',
                'verbose_name_plural': '基础设施实例',
            },
        ),
        migrations.CreateModel(
            name='LabImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='Creator')),
                ('updated_by', models.CharField(default='', max_length=32, verbose_name='Updater')),
                ('domain', models.CharField(default='domain.com', max_length=100, verbose_name='Domain')),
                ('updated_by_domain', models.CharField(default='domain.com', max_length=100, verbose_name='updated by domain')),
                ('name', models.CharField(max_length=100, verbose_name='镜像名称')),
                ('version', models.CharField(max_length=50, verbose_name='镜像版本')),
                ('image_type', models.CharField(choices=[('ide', 'IDE镜像'), ('infra', '基础设施镜像')], max_length=20, verbose_name='镜像类型')),
                ('description', models.TextField(blank=True, null=True, verbose_name='镜像描述')),
                ('image', models.CharField(max_length=200, verbose_name='容器镜像地址')),
                ('default_port', models.IntegerField(default=8888, verbose_name='默认端口')),
                ('default_env', models.JSONField(default=dict, help_text='容器启动时的环境变量', verbose_name='默认环境变量')),
                ('default_command', models.JSONField(default=list, help_text='覆盖镜像的 CMD', verbose_name='默认启动命令')),
                ('default_args', models.JSONField(default=list, help_text='传递给启动命令的参数', verbose_name='默认启动参数')),
                ('expose_ports', models.JSONField(default=list, help_text='需要暴露的端口号列表', verbose_name='暴露端口列表')),
                ('volume_mounts', models.JSONField(default=list, help_text='预定义的卷挂载点', verbose_name='卷挂载配置')),
            ],
            options={
                'verbose_name': 'Lab镜像',
                'verbose_name_plural': 'Lab镜像',
                'unique_together': {('name', 'version', 'image_type')},
            },
        ),
        migrations.CreateModel(
            name='LabEnv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='Creator')),
                ('updated_by', models.CharField(default='', max_length=32, verbose_name='Updater')),
                ('domain', models.CharField(default='domain.com', max_length=100, verbose_name='Domain')),
                ('updated_by_domain', models.CharField(default='domain.com', max_length=100, verbose_name='updated by domain')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='环境名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='环境描述')),
                ('cpu', models.IntegerField(default=2, help_text='CPU核心数量', verbose_name='CPU核数')),
                ('memory', models.CharField(default='4Gi', help_text='如: 4Gi, 8Gi', max_length=20, verbose_name='内存大小')),
                ('gpu', models.IntegerField(default=0, help_text='独占GPU数量', verbose_name='GPU数量')),
                ('volume_size', models.CharField(default='50Gi', help_text='持久化卷大小', max_length=20, verbose_name='存储大小')),
                ('state', models.CharField(choices=[('stopped', '已停止'), ('starting', '启动中'), ('running', '运行中'), ('stopping', '停止中'), ('error', '错误')], default='stopped', max_length=20, verbose_name='环境状态')),
                ('endpoint', models.CharField(blank=True, max_length=200, null=True, verbose_name='访问端点')),
                ('ide_image', models.ForeignKey(limit_choices_to={'image_type': 'ide'}, on_delete=django.db.models.deletion.CASCADE, related_name='lab_envs', to='lab.labimage', verbose_name='IDE镜像')),
                ('infra_instances', models.ManyToManyField(blank=True, related_name='lab_envs', to='lab.infrainstance', verbose_name='基础设施实例')),
            ],
            options={
                'verbose_name': 'Lab环境',
                'verbose_name_plural': 'Lab环境',
            },
        ),
        migrations.AddField(
            model_name='infrainstance',
            name='image',
            field=models.ForeignKey(limit_choices_to={'image_type': 'infra'}, on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='lab.labimage', verbose_name='基础设施镜像'),
        ),
        migrations.AlterUniqueTogether(
            name='infrainstance',
            unique_together={('name',)},
        ),
    ]
