# Generated by Django 4.2.7 on 2025-05-26 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='controllertasknode',
            name='node_name',
            field=models.CharField(default='', max_length=200, verbose_name='节点名称'),
        ),
    ]
