# Generated by Django 4.2.7 on 2025-05-29 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_mgmt', '0002_controllertasknode_node_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidecarenv',
            name='type',
            field=models.CharField(default='', max_length=20),
        ),
    ]
