# Generated by Django 4.2.7 on 2025-06-06 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('node_mgmt', '0003_sidecarenv_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectorConfigurationEnv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='Creator')),
                ('updated_by', models.CharField(default='', max_length=32, verbose_name='Updater')),
                ('env_config', models.JSONField(default=dict, verbose_name='环境变量配置')),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='node_mgmt.collectorconfiguration', verbose_name='采集器配置')),
            ],
            options={
                'verbose_name': '采集器配置环境变量',
                'verbose_name_plural': '采集器配置环境变量',
            },
        ),
    ]
