# Generated by Django 4.2.7 on 2025-06-09 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_mgmt', '0004_collectorconfigurationenv'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectorconfiguration',
            name='env_config',
            field=models.JSONField(default=dict, verbose_name='环境变量配置'),
        ),
        migrations.DeleteModel(
            name='CollectorConfigurationEnv',
        ),
    ]
