# Generated by Django 4.2.7 on 2025-06-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_mgmt', '0005_collectorconfiguration_env_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='childconfig',
            name='env_config',
            field=models.JSONField(default=dict, verbose_name='环境变量配置'),
        ),
    ]
