# Generated by Django 4.2.15 on 2025-06-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_mgmt', '0006_childconfig_env_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='domain',
            field=models.CharField(default='domain.com', max_length=100, verbose_name='Domain'),
        ),
        migrations.AddField(
            model_name='action',
            name='updated_by_domain',
            field=models.CharField(default='domain.com', max_length=100, verbose_name='updated by domain'),
        ),
        migrations.AddField(
            model_name='childconfig',
            name='domain',
            field=models.CharField(default='domain.com', max_length=100, verbose_name='Domain'),
        ),
        migrations.AddField(
            model_name='childconfig',
            name='updated_by_domain',
            field=models.CharField(default='domain.com', max_length=100, verbose_name='updated by domain'),
        ),
        migrations.AddField(
            model_name='cloudregion',
            name='domain',
            field=models.CharField(default='domain.com', max_length=100, verbose_name='Domain'),
        ),
        migrations.AddField(
            model_name='cloudregion',
            name='updated_by_domain',
            field=models.CharField(default='domain.com', max_length=100, verbose_name='updated by domain'),
        ),
        migrations.AddField(
            model_name='collector',
            name='domain',
            field=models.CharField(default='domain.com', max_length=100, verbose_name='Domain'),
        ),
        migrations.AddField(
            model_name='collector',
            name='updated_by_domain',
            field=models.CharField(default='domain.com', max_length=100, verbose_name='updated by domain'),
        ),
        migrations.AddField(
            model_name='collectorconfiguration',
            name='domain',
            field=models.CharField(default='domain.com', max_length=100, verbose_name='Domain'),
        ),
        migrations.AddField(
            model_name='collectorconfiguration',
            name='updated_by_domain',
            field=models.CharField(default='domain.com', max_length=100, verbose_name='updated by domain'),
        ),
        migrations.AddField(
            model_name='collectortask',
            name='domain',
            field=models.CharField(default='domain.com', max_length=100, verbose_name='Domain'),
        ),
        migrations.AddField(
            model_name='collectortask',
            name='updated_by_domain',
            field=models.CharField(default='domain.com', max_length=100, verbose_name='updated by domain'),
        ),
        migrations.AddField(
            model_name='controller',
            name='domain',
            field=models.CharField(default='domain.com', max_length=100, verbose_name='Domain'),
        ),
        migrations.AddField(
            model_name='controller',
            name='updated_by_domain',
            field=models.CharField(default='domain.com', max_length=100, verbose_name='updated by domain'),
        ),
        migrations.AddField(
            model_name='controllertask',
            name='domain',
            field=models.CharField(default='domain.com', max_length=100, verbose_name='Domain'),
        ),
        migrations.AddField(
            model_name='controllertask',
            name='updated_by_domain',
            field=models.CharField(default='domain.com', max_length=100, verbose_name='updated by domain'),
        ),
        migrations.AddField(
            model_name='node',
            name='domain',
            field=models.CharField(default='domain.com', max_length=100, verbose_name='Domain'),
        ),
        migrations.AddField(
            model_name='node',
            name='updated_by_domain',
            field=models.CharField(default='domain.com', max_length=100, verbose_name='updated by domain'),
        ),
        migrations.AddField(
            model_name='nodeorganization',
            name='domain',
            field=models.CharField(default='domain.com', max_length=100, verbose_name='Domain'),
        ),
        migrations.AddField(
            model_name='nodeorganization',
            name='updated_by_domain',
            field=models.CharField(default='domain.com', max_length=100, verbose_name='updated by domain'),
        ),
        migrations.AddField(
            model_name='packageversion',
            name='domain',
            field=models.CharField(default='domain.com', max_length=100, verbose_name='Domain'),
        ),
        migrations.AddField(
            model_name='packageversion',
            name='updated_by_domain',
            field=models.CharField(default='domain.com', max_length=100, verbose_name='updated by domain'),
        ),
        migrations.AddField(
            model_name='sidecarapitoken',
            name='domain',
            field=models.CharField(default='domain.com', max_length=100, verbose_name='Domain'),
        ),
        migrations.AddField(
            model_name='sidecarapitoken',
            name='updated_by_domain',
            field=models.CharField(default='domain.com', max_length=100, verbose_name='updated by domain'),
        ),
    ]
