# Generated by Django 4.2.15 on 2025-07-09 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_mgmt', '0007_action_domain_action_updated_by_domain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collector',
            name='default_config',
            field=models.JSONField(default=dict, verbose_name='默认初始化的配置'),
        ),
        migrations.AddField(
            model_name='collector',
            name='enabled_default_config',
            field=models.BooleanField(default=False, verbose_name='是否启用默认初始化的配置'),
        ),
    ]
