# Generated by Django 4.2.15 on 2025-07-31 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_mgmt', '0008_collector_default_config_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodeorganization',
            name='organization',
            field=models.IntegerField(verbose_name='组织id'),
        ),
    ]
