# Generated by Django 4.2.15 on 2025-08-14 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_mgmt', '0009_alter_nodeorganization_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidecarenv',
            name='is_pre',
            field=models.BooleanField(default=False, verbose_name='是否预置变量'),
        ),
    ]
