# Generated by Django 4.2.15 on 2025-09-08 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_mgmt', '0010_sidecarenv_is_pre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='childconfig',
            options={'ordering': ['sort_order', 'created_at'], 'verbose_name': '子配置', 'verbose_name_plural': '子配置'},
        ),
        migrations.AddField(
            model_name='childconfig',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='排序序号'),
        ),
    ]
