# Generated by Django 4.2.15 on 2025-09-22 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_mgmt', '0011_alter_childconfig_options_childconfig_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidecarapitoken',
            name='node_id',
            field=models.CharField(default='', max_length=100, verbose_name='节点ID'),
        ),
        migrations.AlterField(
            model_name='sidecarapitoken',
            name='token',
            field=models.CharField(max_length=250, verbose_name='Token'),
        ),
    ]
