# Generated by Django 4.2.7 on 2025-06-19 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cmdb", "0006_alter_collectmodels_task_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collectmodels",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("vm", "VM采集"),
                    ("snmp", "SNMP采集"),
                    ("k8s", "K8S采集"),
                    ("cloud", "云采集"),
                    ("protocol", "协议采集"),
                    ("host", "主机采集"),
                    ("redis", "Redis采集"),
                    ("middleware", "中间件采集"),
                    ("ip", "IP采集"),
                    ("other", "其他采集"),
                ],
                help_text="任务类型",
                max_length=32,
            ),
        ),
    ]
