# Generated by Django 4.2.15 on 2025-06-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0007_alter_collectmodels_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectmodels',
            name='domain',
            field=models.CharField(default='domain.com', max_length=100, verbose_name='Domain'),
        ),
        migrations.AddField(
            model_name='collectmodels',
            name='updated_by_domain',
            field=models.CharField(default='domain.com', max_length=100, verbose_name='updated by domain'),
        ),
        migrations.AddField(
            model_name='oidmapping',
            name='domain',
            field=models.CharField(default='domain.com', max_length=100, verbose_name='Domain'),
        ),
        migrations.AddField(
            model_name='oidmapping',
            name='updated_by_domain',
            field=models.CharField(default='domain.com', max_length=100, verbose_name='updated by domain'),
        ),
    ]
