# Generated by Django 4.2.15 on 2025-05-15 06:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_mgmt", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="App",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
                ("display_name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("description_cn", models.TextField(blank=True, null=True)),
                ("icon", models.CharField(blank=True, max_length=100, null=True)),
                ("url", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(max_length=100, unique=True)),
                ("value", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("username", models.CharField(max_length=100, unique=True)),
                ("display_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=128)),
                ("disabled", models.BooleanField(default=False)),
                ("locale", models.CharField(default="zh-Hans", max_length=32)),
                ("timezone", models.CharField(default="Asia/Shanghai", max_length=32)),
                ("group_list", models.JSONField(default=list)),
                ("role_list", models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("app", models.CharField(default="", max_length=50, null=True, blank=True)),
                ("menu_list", models.JSONField(default=list)),
            ],
            options={
                "unique_together": {("name", "app")},
            },
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("display_name", models.CharField(max_length=100)),
                ("url", models.CharField(max_length=255)),
                ("icon", models.CharField(blank=True, max_length=100, null=True)),
                ("order", models.IntegerField(default=0)),
                ("app", models.CharField(default="", max_length=50)),
                ("menu_type", models.CharField(default="", max_length=100)),
            ],
            options={
                "unique_together": {("name", "app")},
            },
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("parent_id", models.IntegerField(default=0)),
            ],
            options={
                "unique_together": {("name", "parent_id")},
            },
        ),
    ]
