# Generated by Django 4.2.15 on 2025-05-19 03:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_mgmt", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="app",
            name="is_build_in",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="temporary_pwd",
            field=models.BooleanField(default=False),
        ),
    ]
