# Generated by Django 4.2.15 on 2025-05-21 02:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_mgmt", "0004_app_is_build_in"),
    ]

    operations = [
        migrations.AddField(
            model_name="app",
            name="tags",
            field=models.JSONField(default=list),
        ),
    ]
