# Generated by Django 4.2.15 on 2025-05-23 09:25

from django.db import migrations, models

import apps.core.mixinx


class Migration(migrations.Migration):
    dependencies = [
        ("system_mgmt", "0005_app_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="otp_secret",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.CreateModel(
            name="LoginModule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("source_type", models.CharField(default="wechat", max_length=50)),
                ("app_id", models.CharField(blank=True, max_length=100, null=True)),
                ("app_secret", models.CharField(blank=True, max_length=100, null=True)),
                ("other_config", models.JSONField(default=list)),
                ("enabled", models.BooleanField(default=True)),
                ("is_build_in", models.BooleanField(default=False)),
            ],
            options={
                "unique_together": {("name", "source_type")},
            },
            bases=(models.Model, apps.core.mixinx.EncryptMixin),
        ),
    ]
