# Generated by Django 4.2.15 on 2025-06-04 07:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_mgmt", "0006_user_otp_secret_loginmodule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loginmodule",
            name="app_secret",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="loginmodule",
            name="other_config",
            field=models.JSONField(default=dict),
        ),
    ]
