# Generated by Django 4.2.15 on 2025-06-05 07:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_mgmt", "0007_alter_loginmodule_app_secret_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupdatarule",
            name="group_id",
            field=models.IntegerField(default=0),
        ),
    ]
