# Generated by Django 4.2.15 on 2025-06-19 08:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_mgmt", "0008_alter_groupdatarule_group_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="external_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="domain",
            field=models.CharField(default="domain.com", max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name="user",
            unique_together={("username", "domain")},
        ),
    ]
