# Generated by Django 4.2.22 on 2025-07-24 06:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("system_mgmt", "0009_group_external_id_user_domain_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="groupdatarule",
            unique_together={("name", "group_id", "app")},
        ),
    ]
