# Generated by Django 4.2.22 on 2025-07-25 07:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_mgmt", "0010_alter_groupdatarule_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="userrule",
            name="domain",
            field=models.CharField(default="domain.com", max_length=100),
        ),
    ]
