# Generated by Django 4.2.15 on 2025-07-04 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='Creator')),
                ('updated_by', models.CharField(default='', max_length=32, verbose_name='Updater')),
                ('domain', models.CharField(default='domain.com', max_length=100, verbose_name='Domain')),
                ('updated_by_domain', models.CharField(default='domain.com', max_length=100, verbose_name='updated by domain')),
                ('name', models.CharField(max_length=100, verbose_name='采集方式')),
                ('collector', models.CharField(max_length=100, verbose_name='采集器')),
                ('icon', models.CharField(max_length=100, verbose_name='图标')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '采集方式',
                'verbose_name_plural': '采集方式',
                'unique_together': {('name', 'collector')},
            },
        ),
        migrations.CreateModel(
            name='CollectInstance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='Creator')),
                ('updated_by', models.CharField(default='', max_length=32, verbose_name='Updater')),
                ('domain', models.CharField(default='domain.com', max_length=100, verbose_name='Domain')),
                ('updated_by_domain', models.CharField(default='domain.com', max_length=100, verbose_name='updated by domain')),
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='采集方式实例ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='采集方式实例名称')),
                ('collect_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.collecttype', verbose_name='采集方式')),
            ],
            options={
                'verbose_name': '采集方式实例',
                'verbose_name_plural': '采集方式实例',
            },
        ),
        migrations.CreateModel(
            name='CollectConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='Creator')),
                ('updated_by', models.CharField(default='', max_length=32, verbose_name='Updater')),
                ('domain', models.CharField(default='domain.com', max_length=100, verbose_name='Domain')),
                ('updated_by_domain', models.CharField(default='domain.com', max_length=100, verbose_name='updated by domain')),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='配置ID')),
                ('file_type', models.CharField(max_length=50, verbose_name='文件类型')),
                ('collect_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.collectinstance', verbose_name='采集方式实例')),
            ],
            options={
                'verbose_name': '采集配置',
                'verbose_name_plural': '采集配置',
            },
        ),
    ]
