# Generated by Django 4.2.15 on 2025-07-11 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectinstance',
            name='node_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Node ID'),
        ),
    ]
