# Generated by Django 4.2.15 on 2025-07-29 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamCollectInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='Creator')),
                ('updated_by', models.CharField(default='', max_length=32, verbose_name='Updater')),
                ('domain', models.CharField(default='domain.com', max_length=100, verbose_name='Domain')),
                ('updated_by_domain', models.CharField(default='domain.com', max_length=100, verbose_name='updated by domain')),
                ('collect_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instance_streams', to='log.collectinstance', verbose_name='采集方式实例')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_instances', to='log.stream', verbose_name='日志数据流')),
            ],
            options={
                'verbose_name': '数据流与采集实例关联',
                'verbose_name_plural': '数据流与采集实例关联',
                'unique_together': {('stream', 'collect_instance')},
            },
        ),
    ]
