# Generated by Django 4.2.15 on 2025-08-12 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0003_alert_event_policy_eventrawdata_event_policy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='notice',
            field=models.BooleanField(default=False, verbose_name='是否已通知'),
        ),
        migrations.AlterField(
            model_name='eventrawdata',
            name='data',
            field=models.JSONField(default=list, verbose_name='原始数据'),
        ),
    ]
