# Generated by Django 4.2.15 on 2025-08-15 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0004_alert_notice_alter_eventrawdata_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='organizations',
        ),
    ]
