# Generated by Django 4.2.15 on 2025-08-20 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0005_remove_policy_organizations'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogGroup',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='Creator')),
                ('updated_by', models.CharField(default='', max_length=32, verbose_name='Updater')),
                ('domain', models.CharField(default='domain.com', max_length=100, verbose_name='Domain')),
                ('updated_by_domain', models.CharField(default='domain.com', max_length=100, verbose_name='updated by domain')),
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='日志分组ID')),
                ('name', models.CharField(max_length=200, verbose_name='日志分组名称')),
                ('rule', models.JSONField(default=dict, verbose_name='规则')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '日志分组',
                'verbose_name_plural': '日志分组',
            },
        ),
        migrations.CreateModel(
            name='LogGroupOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='Creator')),
                ('updated_by', models.CharField(default='', max_length=32, verbose_name='Updater')),
                ('domain', models.CharField(default='domain.com', max_length=100, verbose_name='Domain')),
                ('updated_by_domain', models.CharField(default='domain.com', max_length=100, verbose_name='updated by domain')),
                ('organization', models.IntegerField(verbose_name='组织ID')),
                ('log_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.loggroup', verbose_name='日志分组')),
            ],
            options={
                'verbose_name': '日志分组组织',
                'verbose_name_plural': '日志分组组织',
                'unique_together': {('log_group', 'organization')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='streamcollectinstance',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='streamcollectinstance',
            name='collect_instance',
        ),
        migrations.RemoveField(
            model_name='streamcollectinstance',
            name='stream',
        ),
        migrations.AlterUniqueTogether(
            name='streamorganization',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='streamorganization',
            name='stream',
        ),
        migrations.AddField(
            model_name='policy',
            name='log_groups',
            field=models.JSONField(default=list, help_text='策略监控的日志分组ID列表', verbose_name='日志分组范围'),
        ),
        migrations.DeleteModel(
            name='Stream',
        ),
        migrations.DeleteModel(
            name='StreamCollectInstance',
        ),
        migrations.DeleteModel(
            name='StreamOrganization',
        ),
    ]
