# Generated by Django 4.2.15 on 2025-09-15 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0006_loggroup_loggrouporganization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='Creator')),
                ('updated_by', models.CharField(default='', max_length=32, verbose_name='Updater')),
                ('domain', models.CharField(default='domain.com', max_length=100, verbose_name='Domain')),
                ('updated_by_domain', models.CharField(default='domain.com', max_length=100, verbose_name='updated by domain')),
                ('name', models.CharField(max_length=200, verbose_name='搜索条件名称')),
                ('condition', models.JSONField(default=dict, verbose_name='搜索条件配置')),
                ('organization', models.IntegerField(verbose_name='组织ID')),
            ],
            options={
                'verbose_name': '搜索条件',
                'verbose_name_plural': '搜索条件',
                'ordering': ['-created_at'],
            },
        ),
    ]
