# Generated by Django 4.2.15 on 2025-09-17 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0007_searchcondition'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='show_fields',
            field=models.JSONField(default=list, verbose_name='展示字段'),
        ),
    ]
